version = 3
defaultGlobalExecutorParallelismExpression = "default"

threadPoolPriority = 4
globalExecutorParallelism = 4

[fixes]
	enforceSafeWorldRandomAccess = true
	disableLoggingShutdownHook = "default"

[ioSystem]
	replaceImpl = true
	chunkDataCacheSoftLimit = 16384
	chunkDataCacheLimit = 65536

[vanillaWorldGenOptimizations]
	useDensityFunctionCompiler = true
	optimizeAquifer = true
	useEndBiomeCache = true
	optimizeStructureWeightSampler = true
	enableBuiltinDFCIntegrations = true

[chunkSystem]
	asyncSerialization = true
	recoverFromErrors = false
	allowPOIUnloading = true
	suppressGhostMushrooms = true
	syncPlayerTickets = true
	
	fluidPostProcessingToScheduledTick = true
	filterFluidPostProcessing = true
	useLegacyScheduling = false
	lowMemoryMode = false
	delayFullChunkEvents = true

[generalOptimizations]
	midTickChunkTasksInterval = "default"

	[generalOptimizations.autoSave]
		mode = "ENHANCED"

[noTickViewDistance]
	maxConcurrentChunkLoads = 18
	
	enableExtRenderDistanceProtocol = true
	ensureChunkCorrectness = false
	chunkSendingSpeedMultiplierPercentage = 200

	[clientSideConfig.modifyMaxVDConfig]
		enabled = false
		maxViewDistance = "default"
		enableExtRenderDistanceProtocol = "default"