#Should villagers take offense when you flay the mind of their fellow villagers?
villagersOffendedByMindMurder = true
#Resource locations of dimensions you can't Blink or Greater Teleport in.
tpDimDenyList = ["twilightforest:twilight_forest"]
#When false, makes player reference iotas behave as normal entity reference iotas
doesTrueNameHaveAmbit = true

[Spells]
	#The maximum number of actions that can be executed in one tick, to avoid hanging the server.
	# Default: 100000
	# Range: > 0
	maxOpCount = 100000
	#The harvest level of the Break Block spell.
	#0 = wood, 1 = stone, 2 = iron, 3 = diamond, 4 = netherite.
	# Default: 3
	# Range: 0 ~ 4
	opBreakHarvestLevel = 3
	#Should items fly out of the player's inventory when using Greater Teleport?
	greaterTeleportSplatsItems = true
	#Resource locations of disallowed actions. Trying to cast one of these will result in a mishap. For example, hexcasting:get_caster will prevent Mind's Reflection.
	actionDenyList = []
	#Maps resource locations to the scaling factor for that specific action's media cost. For example, hexcasting:add_motion 3 will make Impulse cost 3x as much.
	costRescaleList = []
	#All media costs, except for actions in the #hexcasting:cannot_modify_cost tag, will be multiplied by this value.If you want to modify the cost of an action in that tag, use the per-action list above.
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	globalCostScaling = 1.0

["Spell Circles"]
	#The maximum number of slates in a spell circle
	# Default: 1024
	# Range: > 4
	maxSpellCircleLength = 1024
	#Resource locations of disallowed actions within circles. Trying to cast one of these in a circle will result in a mishap. For example, hexcasting:get_caster will prevent Mind's Reflection.
	circleActionDenyList = []

[Loot]
	#The chance for wandering traders to sell an Ancient Scroll
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	traderScrollChance = 0.2
