#Wszystkie elementy konfiguracji związane z podstawową rozgrywką
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = true
	#Domyślnie, podczas umieszczania schematu w pobliżu innych budynków, już umieszczone budynki będą wyświetlane tak, jakby były na 5 poziomie i będą otoczone niebieskim konturem. Możesz to wyłączyć, ustawiając to na fałsz. [Default: true]
	neighborbuildingrendering = true
	#Jak blisko musi znajdować się budynek od drugiego, aby można go było uznać za sąsiada, w blokach. -1 = nachodzą na siebie, 0 = dotykają się [Default: 4, min: -2, max: 16]
	# Default: 4
	# Range: -2 ~ 16
	neighborbuildingrange = 4
	#Jak blisko (w blokach) musisz być, aby zobaczyć zlecenia pracy, mając na sobie Gogle Budowlane. [Default: 50, min: 1, max: 250]
	# Default: 50
	# Range: 1 ~ 250
	buildgogglerange = 50
	#Jeśli prawda, granice kolonii wyświetlane podczas trzymania narzędzia budowy będą w kolorze drużyny kolonii. Jeśli jest fałszy, kolonia, w której się znajdujesz, będzie biała, a każda inna kolonia będzie czerwona. [Default: true]
	colonyteamborders = true
	#Czy powinny być wyświetlane specjalne treści świąteczne? [Default: true]
	holidayfeatures = true
