#Wszystkie elementy konfiguracji związane z podstawową rozgrywką
[gameplay]
	#Początkowa ilość mieszkańców. [Default: 4, min: 1, max: 10]
	# Default: 4
	# Range: 1 ~ 10
	initialcitizenamount = 4
	#Gracze powinni mieć możliwość stawiania nieskończonej ilości skrzyń z zasobami? [Default: false]
	allowinfinitesupplychests = false
	#Czy gracze powinni móc łatwo porzucać swoje kolonie na rzecz nowych? Uwaga: to może tworzyć błędy! [Default: false]
	allowinfinitecolonies = false
	#Czy wolno dopuścić kolonie w innych wymiarach? [Default: true]
	allowotherdimcolonies = true
	#Maksymalna ilość mieszkańców w jednej kolonii. [Default: 250, min: 25, max: 500]
	# Default: 250
	# Range: 25 ~ 500
	maxcitizenpercolony = 250
	#Czy funkcje programistyczne powinny być włączone (mogą zawierać błędy)? [Default: false]
	enableindevelopmentfeatures = false
	#Czy znaczniki imion powinny być generowane? [Default: true]
	alwaysrendernametag = true
	#Czy pracownicy powinni pracować podczas deszczu? [Default: false]
	workersalwaysworkinrain = false
	#Szansa na zdobycie rudy przez górnika podczas wydobywania bruku lub kamienia (domyślnie można ją rozszerzyć za pomocą pakietów danych na inne materiały). To jest procent. (Aby zmienić rudy, które może znaleźć Górnik, zobacz „Lista szczęśliwych rud”) [Default: 1, min: 0, max: 100]
	# Default: 1
	# Range: 0 ~ 100
	luckyblockchance = 1
	#Minimalny poziom, jaki musi mieć ratusz, aby umożliwić teleportację do sprzymierzonych kolonii. [Default: 3, min: 0, max: 5]
	# Default: 3
	# Range: 0 ~ 5
	minthleveltoteleport = 3
	#Modyfikator konsumpcji jedzenia. [Default: 1.0, min: 0.1, max: 100.0]
	# Default: 1.0
	# Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#Jak częste są choroby. 1 = Bardzo częste, 100 = niezwykle rzadkie. [Default: 5, min: 1, max: 100]
	# Default: 5
	# Range: 1 ~ 100
	diseasemodifier = 5
	#Jeśli część kolonii jest załadowana przez właściciela/oficera czy kolonia powinna być załadowana? (Ustaw liczbę chunków które mają się ładować używając opcji "Colony Chunk Loading Strictness) [Default: true]
	forceloadcolony = true
	#Ustaw, jak długo chunki pozostają wczytane po odejściu gracza, nie utrzymują się po ponownym uruchomieniu. Domyślnie: 10 min [Default: 10, min: 1, max: 1440]
	# Default: 10
	# Range: 1 ~ 1440
	loadtime = 10
	#Kontroluje to, ile chunków jest ładowanych za pomocą opcji „Chunk Load Colony”. Im wyższa wartość, tym mniej chunków zostanie załadowanych. (Najbardziej wewnętrzne chunki zostaną załadowane jako pierwsze.) 1 = załaduj wszystkie przejęte chunki. [Default: 3, min: 1, max: 15]
	# Default: 3
	# Range: 1 ~ 15
	colonyloadstrictness = 3
	#Maksymalna liczba pni w jednym drzewie, którą Drwal może sprawdzić podczas szukania drzewa. [Default: 400, min: 1, max: 1000]
	# Default: 400
	# Range: 1 ~ 1000
	maxtreesize = 400
	#Wyłącza ograniczenia dotyczące umieszczania obozów z zaopatrzeniem, przeznaczone dla podniebnych światów itp. [Default: false]
	nosupplyplacementrestrictions = false
	#Najeźdźcy będą odradzać się na niebie, jeśli ta opcja jest włączona [Default: false]
	skyraiders = false

#Cała konfiguracja związana z systemem badań
[research]
	#Umożliwia automatyczne i (prawie) natychmiastowe ukończenie badań dla graczy w trybie kreatywnym. Jeśli jest ustawione na fałsz, gracze w trybie kreatywnym nadal będą mogli rozpocząć badania, ale będą mieli normalny czas postępu badań. [Default: true]
	researchcreativecompletion = true
	#Znacząco zwiększa ilość informacji związanych z pakietami danych badawczych, które są rejestrowane podczas ładowania świata. [Default: false]
	researchdebuglog = false
	#Lista przedmiotów pobieranych od graczy podczas cofania już ukończonych badań.
	researchresetcost = ["minecolonies:ancienttome:1"]

#Wszystkie ustawienia związane z komendami w Minecolonies
[commands]
	#Czy gracze powinni mieć możliwość używania komendy: "/mc rtp"? [Default: false]
	canplayerusertpcommand = false
	#Czy gracze powinni mieć możliwość korzystania z komendy: /mc colony teleport? [Default: false]
	canplayerusecolonytpcommand = false
	#Czy gracze mogą teleportować się do sprzymierzonych kolonii? [Default: true]
	canplayeruseallytownhallteleport = true
	#Czy gracze powinni mieć możliwość używania komendy: /mc home? Uwaga: tylko właściciele kolonii mogą używać tej komendy. [Default: false]
	canplayerusehometpcommand = false
	#Czy gracze powinny mieć możliwość używania komendy: /mc colony info? [Default: true]
	canplayeruseshowcolonyinfocommand = true
	#Czy gracze powinni mieć możliwość używania komendy: /mc citizens kill? [Default: false]
	canplayerusekillcitizenscommand = false
	#Czy gracze powinni mieć możliwość używania polecenia /mc citizens modify? [Default: false]
	canplayerusemodifycitizenscommand = false
	#Czy gracze powinni mieć możliwość używania komendy /mc colony addOfficer? [Default: true]
	canplayeruseaddofficercommand = true
	#Czy gracze powinni mieć możliwość korzystania z komendy /mc colony delete? [Default: false]
	canplayerusedeletecolonycommand = false
	#Czy gracz powinien mieć możliwość użycia komendy /mc colony requestsystem-reset? [Default: false]
	canplayeruseresetcommand = false

#Cała konfiguracja związana z roszczeniami kolonii
[claims]
	#minecolonies.config.maxColonySize.comment [Default: 20, min: 1, max: 250]
	# Default: 20
	# Range: 1 ~ 250
	maxColonySize = 20
	#minecolonies.config.minColonyDistance.comment [Default: 8, min: 1, max: 200]
	# Default: 8
	# Range: 1 ~ 200
	minColonyDistance = 8
	#minecolonies.config.initialColonySize.comment [Default: 4, min: 1, max: 15]
	# Default: 4
	# Range: 1 ~ 15
	initialColonySize = 4
	#Maks. odległość (w blokach) dla kolonii od miejsca odrodzenia. [Default: 30000, min: 1000, max: 2147483647]
	# Default: 30000
	# Range: > 1000
	maxdistancefromworldspawn = 30000
	#Mini. odległość (w blokach) dla kolonii od miejsca odrodzenia. [Default: 0, min: 0, max: 1000]
	# Default: 0
	# Range: 0 ~ 1000
	mindistancefromworldspawn = 0

#Wszystkie ustawienia przedmiotów związane z walką w Minecolonies
[combat]
	#minecolonies.config.dobarbariansspawn.comment [Default: true]
	dobarbariansspawn = true
	#minecolonies.config.barbarianhordedifficulty.comment [Default: 5, min: 0, max: 10]
	# Default: 5
	# Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#minecolonies.config.maxBarbarianSize.comment [Default: 80, min: 6, max: 400]
	# Default: 80
	# Range: 6 ~ 400
	maxBarbarianSize = 80
	#minecolonies.config.dobarbariansbreakthroughwalls.comment [Default: true]
	dobarbariansbreakthroughwalls = true
	#Średnia ilość nocy pomiędzy najazdami. [Default: 14, min: 1, max: 50]
	# Default: 14
	# Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#Mini. liczba nocy pomiędzy najazdami. [Default: 10, min: 1, max: 30]
	# Default: 10
	# Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#Czy moby powinny atakować obywateli? [Default: true]
	mobattackcitizens = true
	#minecolonies.config.shouldraiderbreakdoors.comment [Default: true]
	shouldraiderbreakdoors = true
	#Mnożnik obrażeń od ataku dla strażników. [Default: 1.0, min: 0.1, max: 15.0]
	# Default: 1.0
	# Range: 0.1 ~ 15.0
	guardDamageMultiplier = 1.0
	#Mnożnik zdrowia dla całej straży. [Default: 1.0, min: 0.1, max: 5.0]
	# Default: 1.0
	# Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Włącz tryb PvP MineColonies (kolonie mogą zostać zniszczone i nękane pod pewnymi warunkami). [Default: false]
	pvp_mode = false

#Ustawienia wszystkich konfiguracji
[permissions]
	#Czy ochrona kolonii powinna być włączona? [Default: true]
	enablecolonyprotection = true
	#Czy niezależnie od ochrony kolonii należy wyłączyć wybuchy wewnątrz kolonii? DAMAGE_NOTHING całkowicie zapobiega eksplozjom. DAMAGE_PLAYERS, pozwala eksplozjom zadać obrażenia graczom i wrogim mobom, ale nie blokuje ani neutralnych ani przyjaznych bytów. DAMAGE_ENTITIES pozwala na zadanie obrażeń wszystkim bytom. DAMAGE_EVERYTHING pozwala eksplozjom zadawać obrażenia wszystkim, a także niszczyć bloki. [Default: DAMAGE_ENTITIES, values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING]
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#Wyłącza uprawnienia kolonii, jeśli gracz ma określony poziom uprawnień. [Default: 2, min: 0, max: 4]
	# Default: 2
	# Range: 0 ~ 4
	permissioneventbypassminpermlevel = 2

#Wszystkie ustawienia związane ze zgodnością modów
[compatibility]
	#Podczas ładowania receptur generuj audytowe pliki CSV, aby pomóc w debugowaniu pakietów danych lub dodatkowych modyfikacji. [Default: false]
	auditcraftingtags = false
	#Włącz debugowanie ekwipunku. [Default: false]
	debuginventories = false
	#Włącz to, jeśli używasz tego świata do budowania i skanowania planów. [Default: false]
	blueprintbuildmode = false

#Wszystkie ustawienia ścieżek
[pathfinding]
	#Szczegółowość komunikatów debugowania znajdowania ścieżki. [Default: 0, min: 0, max: 10]
	# Default: 0
	# Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Minimalna liczba kolejnych szyn, z których mogą korzystać obywatele. [Default: 8, min: 5, max: 100]
	# Default: 8
	# Range: 5 ~ 100
	minimumrailstopath = 8
	#Liczba dodatkowych wątków, które mają być używane do znajdowania ścieżki. [Default: 1, min: 1, max: 10]
	# Default: 1
	# Range: 1 ~ 10
	pathfindingmaxthreadcount = 1

#minecolonies.config.requestSystem.comment
[requestSystem]
	#Czy system żądań powinien w sposób trybu kreatywnego (jeśli to możliwe) wykonać żądanie, gdy gracz jest zobowiązany do wykonania żądania? Jest to narzędzie do debugowania i wykonywania żądań, może zająć bardzo dużo czasu. [Default: false]
	creativeresolve = false

#minecolonies.config.debugging.comment
[debugging]
	#minecolonies.config.netherworkertakesdamage.comment [Default: true]
	netherworkertakesdamage = true
