version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
extrastorage = true
enderio = true
mcwfences = true
farmersdelight = true
mob_grinding_utils = true
simplemagnets = true
cookingforblockheads = true
laserbridges = true
mcwstairs = true
silentgear = true
redstonepen = true
advanced_ae = true
copycats = true
allthemodium = true
herbsandharvest = true
extradisks = true
domum_ornamentum = true
integratedterminals = true
comforts = true
irons_jewelry = true
allthecompressed = true
alltheores = true
aether = true
morered = true
the_bumblezone = true
ftbquests = true
functionalstorage = true
chisel = true
dysoncubeproject = true
waterframes = true
restrictions = true
rftoolsstorage = true
productivetrees = true
createbigcannons = true
apotheosis = true
dyenamics = true
trophymanager = true
deeperdarker = true
rftoolsbase = true
create = true
buildinggadgets2 = true
minecolonies = true
sfm = true
advancedperipherals = true
glassential = true
biomeswevegone = true
multipiston = true
easy_villagers = true
refinedstorage_mekanism_integration = true
railwaysuntold = true
refinedstorage = true
mcwfurnitures = true
naturesaura = true
dragonlib = true
sophisticatedstorage = true
xnet = true
additional_lights = true
immeng = true
sliceanddice = true
waystones = true
apothic_enchanting = true
dyenamicsandfriends = true
camol = true
pipez = true
disenchanting_table = true
create_power_loader = true
luminax = true
framedblocks = true
megacells = true
everythingcopper = true
xycraft_machines = true
createstockbridge = true
integratedscripting = true
hostilenetworks = true
irons_spellbooks = true
dndecor = true
mcwlights = true
createcobblestone = true
mcwholidays = true
modularbees = true
livingthings = true
pneumaticcraft = true
rootsclassic = true
kubejs = true
mcwdoors = true
sushigocrafting = true
factory_blocks = true
cloudglass = true
little_big_redstone = true
cabletiers = true
pantographsandwires = true
mekanism = true
crystalix = true
refinedtypes = true
productivemetalworks = true
gravestone = true
utilitarian = true
trashcans = true
ars_ocultas = true
create_dragons_plus = true
mininggadgets = true
cobblegengalore = true
ars_additions = true
merequester = true
industrialization_overdrive = true
ae2 = true
draconicevolution = true
ars_nouveau = true
monolib = true
oritech = true
productivebees = true
mekmm = true
pipeorgans = true
fluxnetworks = true
generatorgalore = true
dimstorage = true
compactmachines = true
integratedtunnels = true
mffs = true
alloy_forgery = true
treetap = true
arseng = true
potionsmaster = true
laserio = true
refurbished_furniture = true
pamhc2crops = true
quarryplus = true
actuallyadditions = true
evilcraft = true
powah = true
ars_technica = true
mcwbridges = true
entangled = true
railways = true
handcrafted = true
stevescarts = true
rechiseledcreate = true
modern_industrialization = true
wirelesschargers = true
ars_creo = true
ars_controle = true
merrymaking = true
rftoolsutility = true
supplementaries = true
createbb = true
industrialforegoing = true
createrailwaysnavigator = true
silentgems = true
mahoutsukai = true
rftoolsbuilder = true
minecraft = true
reestrogen = true
railcraft = true
occultism = true
create_connected = true
undergarden = true
just_blahaj = true
createappliedkinetics = true
powergrid = true
twilightforest = true
allthetweaks = true
xtonesreworked = true
rftoolspower = true
enderstorage = true
creeperoverhaul = true
charginggadgets = true
rangedpumps = true
industrialforegoingsouls = true
ironfurnaces = true
bigreactors = true
immersiveengineering = true
createnuclear = true
interdimensionalwirelesstransmitter = true
create_aquatic_ambitions = true
sgearmetalworks = true
integratedcrafting = true
eternal_starlight = true
mcwroofs = true
itemcollectors = true
mysticalagradditions = true
pylons = true
xycraft_override = true
mcwwindows = true
storagedelight = true
securitycraft = true
numismatics = true
connectedglass = true
cataclysm = true
starbunclemania = true
mysticalagriculture = true
create_enchantment_industry = true
mcwpaths = true
createdieselgenerators = true
expandedae = true
farmingforblockheads = true
simplylight = true
xycraft_world = true
bellsandwhistles = true
mcwtrpdoors = true
mekanismgenerators = true
botanypots = true
amendments = true
extended_industrialization = true
moonlight = true
relics = true
integrateddynamics = true
sophisticatedbackpacks = true
appflux = true
torchmaster = true
theurgy = true
chipped = true
sawmill = true
createcasing = true
aquaculture = true
structurize = true
justdirethings = true
modularrouters = true
bibliocraft = true
lootr = true
regions_unexplored = true
iceandfire = true
createdeco = true
elevatorid = true
betterarcheology = true
chromacarvings = true
endermanoverhaul = true
ars_elemental = true
tempad = true
pamhc2trees = true
forbidden_arcanus = true
moderndynamics = true
computercraft = true
sauce = true
reliquary = true
extendedae = true
rechiseled = true
