version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
aeroencasedpipe = true
gnkinetics = true
create_optical = true
galosphere = true
createmetallurgy = true
quark = true
another_furniture = true
easyanvils = true
natures_spirit = true
ecologics = true
copycats = true
dndecor = true
citadel = true
ends_delight = true
fastpaintings = true
railways = true
bellsandwhistles = true
bits_n_bobs = true
amendments = true
createcobblestone = true
mynethersdelight = true
handcrafted = true
moonlight = true
sophisticatedbackpacks = true
alloyed = true
alcohol_industry = true
seamlesssleep = true
offroad = true
naturalist = true
supplementaries = true
createbigcannons = true
create_factory = true
createprism = true
createrailwaysnavigator = true
chipped = true
minersdelight = true
endrem = true
create = true
aeronautics = true
simulated = true
gravestone = true
biomeswevegone = true
struts = true
minecraft = true
paraglider = true
lootr = true
azimuth = true
create_connected = true
createdeco = true
betterarcheology = true
sliceanddice = true
createframed = true
dragonlib = true
enchantinginfuser = true
soulless = true
pipeorgans = true
